# Generated by Django 4.2.7 on 2023-11-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название шаблона')),
                ('name_field', models.CharField(max_length=256, verbose_name='Имя поля')),
                ('type_field', models.CharField(choices=[('email', 'Email'), ('date', 'Date'), ('phone', 'Phone'), ('text', 'Text')], max_length=5, verbose_name='Тип поля')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
    ]
